### ISSUE TITLE
Порядок вопросов и опечатки

### ISSUE THREAD

**Issue by Dok11** [Angular-RU/angular-ru-interview-questions#2]
1. Вопросы упорядочены по сложности?
Похоже, что нет.. почему?
2. `Какие различные способы использования шаблонов в Angular вы знаете?`
Скорее всего, «различные» здесь лишнее.
3. `Каким должна быть структуру каталогов компонентов любого Angular приложения и почему?`  
наверное, так: `Какой должна быть структура каталогов компонентов любого Angular приложения и почему?`
4. `Как обовлять представление, если ваша модель данных обновляется вне зоны?`  
=> `Как обновлять представление, если ваша модель данных обновляется вне зоны?`

**Comment by splincode** [comment]
- Вопросы упорядочены по сложности?
похоже, что нет, вопросы были собраны изначально в черновом варианте, также предполагается, сразу дать ответы на них

**Comment by splincode** [comment]
1. Изменен порядок вопросов и группировка
2. Исправлены опечатки
